### PR TITLE
Oli/profile

### PR DESCRIPTION
**Pull request by oli-lane**
Summary: profile page, edit username/email functionality, not linked to backend

### CODE REVIEW

**Comment by halliec6** [comment]
Nice job, randomizing profile pictures was a great addition. In sprint 3 make sure to separate friends into "followers" and "following" since we aren't making relationships mutual.  For example, Spotify does this on their profiles page:
image

**Comment by oli-lane** [comment]
Will do, thanks for the feedback!

**Comment by clkodd** [comment]
looks clean! i like that you can just edit username right on the page.

**Comment by ryanchansf** [comment]
Thanks for doing this Oli! The app is truly coming together :)

**Pull request merged**
