### PR TITLE
Following page

### LINKED ISSUE #44: Create friends page
**Description**
- make friends page in navbar clickable
- followers and following displayed based on who is logged in
- frontend and backend copnnected

### PR DESCRIPTION
**Pull request by halliec6**
## Developer: Hallie Christophers
Closes #44

### Pull Request Summary

create friends page and connect frontend and backend
### Modifications

- created friends page
- followers and following api

### Testing Considerations
- checked with database to make sure correct users were showed
{list out what you have tested and what the reviewer should verify}

### Screenshots/Screencast
image

{put screenshots of your change, or even better a screencast displaying the functionality}

### CODE REVIEW

**Comment by athapar9** [comment]
Good job on the followers page, it looks great so far! Just be sure to debug the post endpoint so that it works as intended in the backend.

**Comment by clkodd** [comment]
love the layout of the page!!

**Comment by ryanchansf** [comment]
Awesome stuff, huge milestone for our Sprint 2 progress. Also, thanks for adding the screenshot in the PR —  helped a bunch!

**Comment by halliec6** [comment]
@athapar9  will do, next PR has these bugs fixed, thank you for pointing that out

**Pull request merged**
