### PR TITLE
AuthN flow

### LINKED ISSUE #12: Implement access control (AuthN and AuthZ)
Implement authentication in the project.

- [x] Create Login page
- [x] Create Register page
- [x] Implement auth endpoints for `/login`, `/register`
- [x] Implement [NextAuth.js](https://next-auth.js.org/) or [Clerk.js](https://clerk.com/docs/authentication/configuration/sign-up-options)

Assignment spec: https://canvas.calpoly.edu/courses/121445/assignments/896883

### PR DESCRIPTION
**Pull request by ryanchansf**
## Developer: Ryan Chan

Closes #12

### Pull Request Summary

Implementation of access control for the website

### Modifications

- [x] Create endpoints for creating user, updating user, fetching users or specific user based on `username` query parameter
- [x] Add `/register` page that has both Login and Register card components
- [x] Implement NextAuth to handle authentication and session persistence across pages
- [x] Modify Navbar to have logout button, fix it at the bottom of the screen
- [x] Add conditional rendering for Register/Login flow
- [x] Modify and refactor home page header to include authenticated username
- [x] Add toast components to indicate `Successful registration`, `Invalid credentials`, and `Account already exists` messages for registration/login events
- [x] Add minor styling modifications to make Navbar icons move upon hover
NOTE: Google OAuth is currently listed as a sign in option, but is not currently implemented. It will be a nice to have if we can get to it later

### Testing Considerations

- All API routes tested via Postman
- Authentication manually tested in UI

### Pull Request Checklist

- [x] Code is neat, readable, and works
- [x] Comments are appropriate
- [x] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [x] The developer name is specified
- [x] The summary is completed
- [x] Assign reviewers

### Screenshots/Screencast
N/A (run branch in dev environment to test it out)

**NOTE: you will now need to add these credentials to your `.env`** 
`NEXTAUTH_URL=http://localhost:3000`
`NEXTAUTH_SECRET=tgyuiytrfed4frgty`

### CODE REVIEW

**Comment by halliec6** [comment]
Thanks for clearly explaining your changes, great work on this part of the project.

**Comment by clkodd** [comment]
that was a hefty commit! thanks for doing all that, i know it's really important for our project so im glad you got it down. looks grand

**Comment by athapar9** [comment]
Love the detailed PR. Thanks for taking the time to do this, the code looks amazing!

**Comment by ryanchansf** [comment]
> that was a hefty commit! thanks for doing all that, i know it's really important for our project so im glad you got it down. looks grand

Yeah — I think next time I'll try to split this work up incrementally into smaller PRs. Would make it easier for you guys to review! Thanks for looking over this everyone.

**Pull request merged**
